In [1]:
import numpy as np
from esg import EconomicScenarioGenerator

In [17]:
corr = np.array([[1.0, -0.6, 0.3], [-0.6, 1.0, 0.02], [0.3, 0.02, 1.0]])
headers = "['AK_SV', 'AK_WORLD', 'RB5']"
s0 = np.array([393.0, 275.1, 8.5])
ar = np.array([0.0, 0.0, 1.0])
mu = np.array([0.2, 0.2, 8.5])
sigma = np.array([0.026, 0.026, 0.4])

In [18]:
N,t_steps, partition = 100000, 24, 12
ESG = EconomicScenarioGenerator(s0, ar, mu, sigma, corr)

In [19]:
S = ESG.get_scenarios(N,t_steps, partition)

In [20]:
S.shape

(100000, 24, 3)

In [21]:
S[:2,:4,:]

array([[[393.        , 275.1       ,   8.5       ],
        [400.88888964, 278.23227366,   8.66764363],
        [411.60461522, 280.53622026,   8.67007979],
        [420.44918091, 283.94628935,   8.71309236]],

       [[393.        , 275.1       ,   8.5       ],
        [396.29262826, 280.78812155,   8.64989007],
        [398.67952267, 286.68248517,   8.56682119],
        [400.76532204, 293.80936799,   8.42900228]]])

In [22]:
simCorr = np.zeros((N,S.shape[2],S.shape[2]))
for n in range(N):
    dS = np.diff(S[n], axis=0)
    dS[:,:2] = np.diff(np.log(S[n,:,:2]), axis=0)
    simCorr[n] = np.corrcoef(dS, rowvar=False)

In [23]:
np.mean(simCorr,axis=0)

array([[ 1.        , -0.59082072,  0.29241335],
       [-0.59082072,  1.        ,  0.018175  ],
       [ 0.29241335,  0.018175  ,  1.        ]])

In [24]:
corr

array([[ 1.  , -0.6 ,  0.3 ],
       [-0.6 ,  1.  ,  0.02],
       [ 0.3 ,  0.02,  1.  ]])