In [1]:
import numpy as np

In [57]:
a = np.arange(1, 49).reshape((24, 2), order='F')
b = np.arange(49, 97).reshape((24, 2), order='F')
c = np.arange(97, 145).reshape((24, 2), order='F')

In [58]:
a

array([[ 1, 25],
       [ 2, 26],
       [ 3, 27],
       [ 4, 28],
       [ 5, 29],
       [ 6, 30],
       [ 7, 31],
       [ 8, 32],
       [ 9, 33],
       [10, 34],
       [11, 35],
       [12, 36],
       [13, 37],
       [14, 38],
       [15, 39],
       [16, 40],
       [17, 41],
       [18, 42],
       [19, 43],
       [20, 44],
       [21, 45],
       [22, 46],
       [23, 47],
       [24, 48]])

In [59]:
b

array([[49, 73],
       [50, 74],
       [51, 75],
       [52, 76],
       [53, 77],
       [54, 78],
       [55, 79],
       [56, 80],
       [57, 81],
       [58, 82],
       [59, 83],
       [60, 84],
       [61, 85],
       [62, 86],
       [63, 87],
       [64, 88],
       [65, 89],
       [66, 90],
       [67, 91],
       [68, 92],
       [69, 93],
       [70, 94],
       [71, 95],
       [72, 96]])

In [60]:
c

array([[ 97, 121],
       [ 98, 122],
       [ 99, 123],
       [100, 124],
       [101, 125],
       [102, 126],
       [103, 127],
       [104, 128],
       [105, 129],
       [106, 130],
       [107, 131],
       [108, 132],
       [109, 133],
       [110, 134],
       [111, 135],
       [112, 136],
       [113, 137],
       [114, 138],
       [115, 139],
       [116, 140],
       [117, 141],
       [118, 142],
       [119, 143],
       [120, 144]])

In [61]:
d3 = np.array([a, b, c])

In [62]:
d3[0]

array([[ 1, 25],
       [ 2, 26],
       [ 3, 27],
       [ 4, 28],
       [ 5, 29],
       [ 6, 30],
       [ 7, 31],
       [ 8, 32],
       [ 9, 33],
       [10, 34],
       [11, 35],
       [12, 36],
       [13, 37],
       [14, 38],
       [15, 39],
       [16, 40],
       [17, 41],
       [18, 42],
       [19, 43],
       [20, 44],
       [21, 45],
       [22, 46],
       [23, 47],
       [24, 48]])

In [63]:
d3.shape

(3, 24, 2)

In [69]:
A = d3.reshape(-1, d3.shape[-1])

In [70]:
A

array([[  1,  25],
       [  2,  26],
       [  3,  27],
       [  4,  28],
       [  5,  29],
       [  6,  30],
       [  7,  31],
       [  8,  32],
       [  9,  33],
       [ 10,  34],
       [ 11,  35],
       [ 12,  36],
       [ 13,  37],
       [ 14,  38],
       [ 15,  39],
       [ 16,  40],
       [ 17,  41],
       [ 18,  42],
       [ 19,  43],
       [ 20,  44],
       [ 21,  45],
       [ 22,  46],
       [ 23,  47],
       [ 24,  48],
       [ 49,  73],
       [ 50,  74],
       [ 51,  75],
       [ 52,  76],
       [ 53,  77],
       [ 54,  78],
       [ 55,  79],
       [ 56,  80],
       [ 57,  81],
       [ 58,  82],
       [ 59,  83],
       [ 60,  84],
       [ 61,  85],
       [ 62,  86],
       [ 63,  87],
       [ 64,  88],
       [ 65,  89],
       [ 66,  90],
       [ 67,  91],
       [ 68,  92],
       [ 69,  93],
       [ 70,  94],
       [ 71,  95],
       [ 72,  96],
       [ 97, 121],
       [ 98, 122],
       [ 99, 123],
       [100, 124],
       [101,

In [66]:
A.shape

(6, 24)